### ISSUE TITLE
invalid message format

### ISSUE THREAD

**Issue by matthewberryman** [urbanriskmap/cognicity-server#10]
I guess a SQL statement is messed up? Need more info on what requests are generating these.
This is all I get in the logs:
2017-01-04T01:23:40.599Z - error:  error: invalid message format
    at Connection.parseE (/var/app/current/node_modules/pg/lib/connection.js:539:11)
    at Connection.parseMessage (/var/app/current/node_modules/pg/lib/connection.js:366:17)
    at TLSSocket.<anonymous> (/var/app/current/node_modules/pg/lib/connection.js:105:22)
    at emitOne (events.js:96:13)
    at TLSSocket.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:176:18)
    at TLSSocket.Readable.push (_stream_readable.js:134:10)
    at TLSWrap.onread (net.js:548:20)

**Comment by mgvarley** [comment]
@matthewberryman is this is in prod?  I can see it is in amber status in Beanstalk.  I have set the environment variable LOG_LEVEL to debug (default is error in prod) which should give us a bit more context.

**Comment by mgvarley** [comment]
Here is an example of a query that is generating the issue, @talltom would you be able to have a look?  Not sure if the DB schema has changed or if it is just an issue with real data differing from the test data we were using.  A quick Google on the error suggests that the root cause is a difference between the way we are passing the query to the DB which results in a not very friendly or useful error from node-pg.

```
INSERT INTO qlue.reports
		 	(post_id, created_at, disaster_type, text, image_url, title, qlue_city, the_geom)
			VALUES ($1, $2, $3, $4, $5, $6, $7, ST_SetSRID(ST_Point($8,$9),4326)) 0=843649, 1=Wed Jan 04 2017 13:36:00 GMT+0000 (UTC), 2=flood, 3=Tol dikertuk banyak saluran yg mampat di belakang St kereta semanan, 4=https://lh3.googleusercontent.com/XIaSgn6nWnfAsU5N9OsbmmbKPUsNLKqh09SyQfFD0qUan_eBv1Ye9xTEin4w1fo_C3mgK9RxWcxX_1TYXdURsh4ixyRAmA=s480-c, 5= , 6=jabodetabek, 7=106.699272, 8=-6.16456
```

**Comment by tomasholderness** [comment]
Here's a copy of the raw Qlue report: https://gist.github.com/talltom/bad039aec7d2e155d4241d7e5e547175

**Comment by tomasholderness** [comment]
Further investigation leads me to question why the date is formatted as it is in @mgvarley's query.

The created_at parameter is converted to an ISO string in the Lambda here: https://github.com/urbanriskmap/cognicity-reports-lambda/blob/master/qlue/QlueLambda.js#L36 And I can't see why it would be formatted as such. 

I also downloaded the latest logs but couldn't see any reference to this error. @matthewberryman now that the log level has been changed, please send further examples through when you get them.

**Comment by matthewberryman** [comment]
Here's the lead-up to one on prod:
```
2017-01-04T23:48:40.316Z - debug: INSERT INTO qlue.reports
                        (post_id, created_at, disaster_type, text, image_url, title, qlue_city, the_geom)
                        VALUES ($1, $2, $3, $4, $5, $6, $7, ST_SetSRID(ST_Point($8,$9),4326)) 0=843252, 1=Wed Jan 04 2017 06:49:00 GMT+0000 (UTC), 2=flood, 3=#drainaseburuk, ru
mli rawan banjir, 4=https://lh3.googleusercontent.com/SpFIfK95InDFTJSLG2VVEgsAMmK6Lv2gKrot4N_b_UJlLRhPinPcr78Yz7Ph8-4qoQGFcJzDgUqH5UuESQ0xmTsqiJ1v=s480-c, 5= , 6=jabodetabek, 7
=106.926819, 8=-6.119712
2017-01-04T23:48:40.319Z - debug: INSERT INTO qlue.reports
                        (post_id, created_at, disaster_type, text, image_url, title, qlue_city, the_geom)
                        VALUES ($1, $2, $3, $4, $5, $6, $7, ST_SetSRID(ST_Point($8,$9),4326)) 0=842857, 1=Tue Jan 03 2017 16:01:00 GMT+0000 (UTC), 2=flood, 3=Keadaan saluran ai
r di Rt 009/05 Rorotan, agar di Normalisasi., 4=https://lh3.googleusercontent.com/8t5OZzjafBAJcEwsT28iIFQkuVQ9DBl6TV7Fs72o3L_YPOhgAVRqDE8VWMJ4PlFD0NXSu8_hrRqkMkbNK-zPDjwgaUG4=s
480-c, 5= , 6=jabodetabek, 7=106.955765, 8=-6.141429
2017-01-04T23:48:40.320Z - info: ::ffff:127.0.0.1 - - [04/Jan/2017:23:48:40 +0000] "POST /feeds/qlue HTTP/1.1" 200 85 "-" "AmazonAPIGateway_m8v4hq8kec"
2017-01-04T23:48:40.327Z - info: ::ffff:127.0.0.1 - - [04/Jan/2017:23:48:40 +0000] "POST /feeds/qlue HTTP/1.1" 200 85 "-" "AmazonAPIGateway_m8v4hq8kec"
2017-01-04T23:48:40.350Z - info: ::ffff:127.0.0.1 - - [04/Jan/2017:23:48:40 +0000] "POST /feeds/qlue HTTP/1.1" 200 85 "-" "AmazonAPIGateway_m8v4hq8kec"
2017-01-04T23:48:40.373Z - info: ::ffff:127.0.0.1 - - [04/Jan/2017:23:48:40 +0000] "POST /feeds/qlue HTTP/1.1" 200 85 "-" "AmazonAPIGateway_m8v4hq8kec"
2017-01-04T23:48:40.374Z - error:  error: invalid message format
    at Connection.parseE (/var/app/current/node_modules/pg/lib/connection.js:539:11)
    at Connection.parseMessage (/var/app/current/node_modules/pg/lib/connection.js:366:17)
    at TLSSocket.<anonymous> (/var/app/current/node_modules/pg/lib/connection.js:105:22)
    at emitOne (events.js:96:13)
    at TLSSocket.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:176:18)
    at TLSSocket.Readable.push (_stream_readable.js:134:10)
    at TLSWrap.onread (net.js:548:20)
```
