### ISSUE TITLE
Request report ID returns 500 internal server error

### ISSUE THREAD

**Issue by tomasholderness** [urbanriskmap/cognicity-server#11]
https://data-dev.petabencana.id/reports/180480

returns:
```
{"status":500,"stack":"TypeError: data.map is not a function\n    at Object.dbgeo.parse (/var/app/current/node_modules/dbgeo/lib/dbgeo.js:47:22)\n    at /var/app/current/dist/lib/util.js:72:21\n    at formatGeo (/var/app/current/dist/lib/util.js:71:10)\n    at handleGeoResponse (/var/app/current/dist/lib/util.js:82:90)\n    at /var/app/current/dist/api/routes/reports/index.js:61:39\nFrom previous event:\n    at /var/app/current/dist/api/routes/reports/index.js:60:71\n    at Layer.handle [as handle_request] (/var/app/current/node_modules/express/lib/router/layer.js:95:5)\n    at next (/var/app/current/node_modules/express/lib/router/route.js:131:13)\n    at ResultsHolder.release (/var/app/current/node_modules/fastseries/series.js:99:22)\n    at /var/app/current/node_modules/celebrate/lib/index.js:52:18\n    at makeCall (/var/app/current/node_modules/fastseries/series.js:119:7)\n    at ResultsHolder.release (/var/app/current/node_modules/fastseries/series.js:96:9)\n    at Joi.validate (/var/app/current/node_modules/celebrate/lib/index.js:37:16)\n    at _validateWithOptions (/var/app/current/node_modules/joi/lib/any.js:610:20)\n    at root.validate (/var/app/current/node_modules/joi/lib/index.js:121:23)\n    at /var/app/current/node_modules/celebrate/lib/index.js:28:11\n    at makeCall (/var/app/current/node_modules/fastseries/series.js:119:7)\n    at ResultsHolder.release (/var/app/current/node_modules/fastseries/series.js:96:9)\n    at Joi.validate (/var/app/current/node_modules/celebrate/lib/index.js:37:16)\n    at _validateWithOptions (/var/app/current/node_modules/joi/lib/any.js:610:20)\n    at root.validate (/var/app/current/node_modules/joi/lib/index.js:121:23)\n    at /var/app/current/node_modules/celebrate/lib/index.js:28:11\n    at makeCall (/var/app/current/node_modules/fastseries/series.js:119:7)\n    at ResultsHolder.release (/var/app/current/node_modules/fastseries/series.js:96:9)","message":"Internal Server Error"}
```

**Comment by tomasholderness** [comment]
- dbgeo.parse requires an array (https://www.npmjs.com/package/dbgeo#parsedata-options-callback)
- in this case db.oneOrNone returns an object
- we could add a test for array type in util.formatGeo before calling dbgeo.parse (http://stackoverflow.com/questions/4775722/check-if-object-is-array)
