### ISSUE TITLE
TypeError

### ISSUE THREAD

**Issue by matthewberryman** [urbanriskmap/cognicity-server#2]
TypeError: First argument must be a string, Buffer, ArrayBuffer, Array, or array-like object.
    at fromObject (buffer.js:262:9)
    at Function.Buffer.from (buffer.js:101:10)
    at new Buffer (buffer.js:80:17)
    at Object.<anonymous> (/var/app/current/dist/lib/util.js:40:11)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/var/app/current/dist/api/routes/cards/index.js:13:13)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
buffer.js:262
  throw new TypeError(kFromErrorMsg);
  ^

**Comment by matthewberryman** [comment]
Error is because code's been deployed requiring AUTH0 environment variables to be set but these weren't set in the Elastic Beanstalk environment. I will update now.

**Comment by mgvarley** [comment]
OK cool, will include a check for these on launch and exit the server if they’re not there.


Thanks,


Mark




>

**Comment by matthewberryman** [comment]
Exiting the server will send EB / PM2 into an infinite restart loop. Best to avoid that. It's fine as is - it logs an error and can be diagnosed.
