### ISSUE TITLE
column reference wrong / column missing

### ISSUE THREAD

**Issue by matthewberryman** [urbanriskmap/cognicity-server#79]
Got an email notification about a 503 on data.riskmap.in, here's the error from the server logs
```
2018-01-24T09:50:15.816Z - error:  error: column la.district_id does not exist
    at Connection.parseE (/var/app/current/node_modules/pg/lib/connection.js:539:11)
    at Connection.parseMessage (/var/app/current/node_modules/pg/lib/connection.js:366:17)
    at TLSSocket.<anonymous> (/var/app/current/node_modules/pg/lib/connection.js:105:22)
    at emitOne (events.js:116:13)
    at TLSSocket.emit (events.js:211:7)
    at addChunk (_stream_readable.js:263:12)
    at readableAddChunk (_stream_readable.js:250:11)
    at TLSSocket.Readable.push (_stream_readable.js:208:10)
    at TLSWrap.onread (net.js:594:20)
```

**Comment by tomasholderness** [comment]
Fixed over in the schema. https://github.com/urbanriskmap/cognicity-schema/issues/43
