### ISSUE TITLE
missing column in database

### ISSUE THREAD

**Issue by matthewberryman** [urbanriskmap/cognicity-server#84]
```
2018-03-28T22:01:11.788Z - error:  BatchError {
    stat: { total: 3, succeeded: 0, failed: 3, duration: 57 }
    errors: [
        0: { error: column "district_id" does not exist
            at Connection.parseE (/var/app/current/node_modules/pg/lib/connection.js:539:11)
            at Connection.parseMessage (/var/app/current/node_modules/pg/lib/connection.js:366:17)
            at TLSSocket.<anonymous> (/var/app/current/node_modules/pg/lib/connection.js:105:22)
            at emitOne (events.js:116:13)
            at TLSSocket.emit (events.js:211:7)
            at addChunk (_stream_readable.js:263:12)
            at readableAddChunk (_stream_readable.js:250:11)
            at TLSSocket.Readable.push (_stream_readable.js:208:10)
            at TLSWrap.onread (net.js:594:20)
        From previous event:
            at promise (/var/app/current/node_modules/pg-promise/lib/promise.js:23:20)
            at Task.$query (/var/app/current/node_modules/pg-promise/lib/query.js:128:12)
            at Task.<anonymous> (/var/app/current/node_modules/pg-promise/lib/query.js:231:23)
            at Task.query (/var/app/current/node_modules/pg-promise/lib/task.js:119:34)
            at Task.obj.none (/var/app/current/node_modules/pg-promise/lib/database.js:368:30)
            at /var/app/current/dist/api/routes/cards/model.js:1129:22
            at Array.map (<anonymous>)
            at Task.<anonymous> (/var/app/current/dist/api/routes/cards/model.js:1126:34)
            at callback (/var/app/current/node_modules/pg-promise/lib/task.js:188:25)
            at begin.then (/var/app/current/node_modules/pg-promise/lib/task.js:233:28)
        From previous event:
            at Function.Task.exec (/var/app/current/node_modules/pg-promise/lib/task.js:232:14)
            at config.$npm.connect.pool.then.db (/var/app/current/node_modules/pg-promise/lib/database.js:1219:45)
        From previous event:
            at Database.taskProcessor (/var/app/current/node_modules/pg-promise/lib/database.js:1216:18)
            at Database.obj.tx (/var/app/current/node_modules/pg-promise/lib/database.js:1159:34)
            at /var/app/current/dist/api/routes/cards/model.js:1122:12
        From previous event:
            at Object.submitReport (/var/app/current/dist/api/routes/cards/model.js:1079:14)
            at /var/app/current/dist/api/routes/cards/index.js:1702:56
            at runCallback (timers.js:789:20)
            at tryOnImmediate (timers.js:751:5)
            at processImmediate [as _immediateCallback] (timers.js:722:5)
        From previous event:
            at /var/app/current/dist/api/routes/cards/index.js:1675:76
            at Layer.handle [as handle_request] (/var/app/current/node_modules/express/lib/router/layer.js:95:5)
            at next (/var/app/current/node_modules/express/lib/router/route.js:137:13)
            at ResultsHolder.release (/var/app/current/node_modules/fastseries/series.js:99:22)
            at Joi.validate (/var/app/current/node_modules/celebrate/lib/index.js:37:16)
            at internals.Object._validateWithOptions (/var/app/current/node_modules/joi/lib/types/any/index.js:654:20)
            at module.exports.internals.Any.root.validate (/var/app/current/node_modules/joi/lib/index.js:121:23)
            at /var/app/current/node_modules/celebrate/lib/index.js:28:11
            at /var/app/current/node_modules/celebrate/lib/index.js:53:9
            at makeCall (/var/app/current/node_modules/fastseries/series.js:119:7)
            at ResultsHolder.release (/var/app/current/node_modules/fastseries/series.js:96:9)
            at /var/app/current/node_modules/celebrate/lib/index.js:25:16
            at makeCall (/var/app/current/node_modules/fastseries/series.js:119:7)
            at ResultsHolder.release (/var/app/current/node_modules/fastseries/series.js:96:9)
            at Joi.validate (/var/app/current/node_modules/celebrate/lib/index.js:37:16)
            at internals.Object._validateWithOptions (/var/app/current/node_modules/joi/lib/types/any/index.js:654:20)
            at module.exports.internals.Any.root.validate (/var/app/current/node_modules/joi/lib/index.js:121:23)
            at /var/app/current/node_modules/celebrate/lib/index.js:28:11
            at makeCall (/var/app/current/node_modules/fastseries/series.js:119:7)
          name: 'error',
          length: 1262,
          severity: 'ERROR',
          code: '42703',
          detail: undefined,
          hint: undefined,
          position: undefined,
          internalPosition: '253',
          internalQuery: 'UPDATE cognicity.all_reports\n    SET tags = (SELECT (la.x->0)::jsonb || (code.x->0)::jsonb FROM (SELECT COALESCE(array_to_json(array_agg(row_to_json(a))),\'[{"local_area_id":null, "district_id":null}]\') as x FROM (SELECT pkey::varchar as local_area_id, district_id::varchar as district_id FROM cognicity.local_areas as j WHERE ST_Within(NEW.the_geom, j.the_geom)) as a) as la, (SELECT COALESCE(array_to_json(array_agg(row_to_json(a))),\'[{"instance_region_code":null}]\') as x FROM (SELECT code as instance_region_code FROM cognicity.instance_regions as i WHERE ST_Within(NEW.the_geom, i.the_geom)) as a) as code)\n    WHERE pkey = NEW.pkey',
          where: 'PL/pgSQL function cognicity.define_report_region() line 3 at SQL statement\nSQL statement "INSERT INTO cognicity.all_reports (fkey, created_at, text, source, disaster_type, lang, url, report_data, the_geom, image_url)\n      SELECT NEW.pkey, NEW.created_at, NEW.text, \'grasp\', NEW.disaster_type, card.language, card.card_id, NEW.card_data, NEW.the_geom, NEW.image_url\n      FROM grasp.cards AS card WHERE card.card_id = NEW.card_id"\nPL/pgSQL function grasp.update_all_reports_from_grasp() line 7 at SQL statement',
          schema: undefined,
          table: undefined,
          column: undefined,
          dataType: undefined,
          constraint: undefined,
          file: 'parse_relation.c',
          line: '3293',
          routine: 'errorMissingColumn' }
        1: { error: current transaction is aborted, commands ignored until end of transaction block
            at Connection.parseE (/var/app/current/node_modules/pg/lib/connection.js:539:11)
            at Connection.parseMessage (/var/app/current/node_modules/pg/lib/connection.js:366:17)
            at TLSSocket.<anonymous> (/var/app/current/node_modules/pg/lib/connection.js:105:22)
            at emitOne (events.js:116:13)
            at TLSSocket.emit (events.js:211:7)
            at addChunk (_stream_readable.js:263:12)
            at readableAddChunk (_stream_readable.js:250:11)
            at TLSSocket.Readable.push (_stream_readable.js:208:10)
            at TLSWrap.onread (net.js:594:20)
        From previous event:
            at promise (/var/app/current/node_modules/pg-promise/lib/promise.js:23:20)
            at Task.$query (/var/app/current/node_modules/pg-promise/lib/query.js:128:12)
            at Task.<anonymous> (/var/app/current/node_modules/pg-promise/lib/query.js:231:23)
            at Task.query (/var/app/current/node_modules/pg-promise/lib/task.js:119:34)
            at Task.obj.none (/var/app/current/node_modules/pg-promise/lib/database.js:368:30)
            at /var/app/current/dist/api/routes/cards/model.js:1129:22
            at Array.map (<anonymous>)
            at Task.<anonymous> (/var/app/current/dist/api/routes/cards/model.js:1126:34)
            at callback (/var/app/current/node_modules/pg-promise/lib/task.js:188:25)
            at begin.then (/var/app/current/node_modules/pg-promise/lib/task.js:233:28)
        From previous event:
            at Function.Task.exec (/var/app/current/node_modules/pg-promise/lib/task.js:232:14)
            at config.$npm.connect.pool.then.db (/var/app/current/node_modules/pg-promise/lib/database.js:1219:45)
        From previous event:
            at Database.taskProcessor (/var/app/current/node_modules/pg-promise/lib/database.js:1216:18)
            at Database.obj.tx (/var/app/current/node_modules/pg-promise/lib/database.js:1159:34)
            at /var/app/current/dist/api/routes/cards/model.js:1122:12
        From previous event:
            at Object.submitReport (/var/app/current/dist/api/routes/cards/model.js:1079:14)
            at /var/app/current/dist/api/routes/cards/index.js:1702:56
            at runCallback (timers.js:789:20)
            at tryOnImmediate (timers.js:751:5)
            at processImmediate [as _immediateCallback] (timers.js:722:5)
        From previous event:
            at /var/app/current/dist/api/routes/cards/index.js:1675:76
            at Layer.handle [as handle_request] (/var/app/current/node_modules/express/lib/router/layer.js:95:5)
            at next (/var/app/current/node_modules/express/lib/router/route.js:137:13)
            at ResultsHolder.release (/var/app/current/node_modules/fastseries/series.js:99:22)
            at Joi.validate (/var/app/current/node_modules/celebrate/lib/index.js:37:16)
            at internals.Object._validateWithOptions (/var/app/current/node_modules/joi/lib/types/any/index.js:654:20)
            at module.exports.internals.Any.root.validate (/var/app/current/node_modules/joi/lib/index.js:121:23)
            at /var/app/current/node_modules/celebrate/lib/index.js:28:11
            at /var/app/current/node_modules/celebrate/lib/index.js:53:9
            at makeCall (/var/app/current/node_modules/fastseries/series.js:119:7)
            at ResultsHolder.release (/var/app/current/node_modules/fastseries/series.js:96:9)
            at /var/app/current/node_modules/celebrate/lib/index.js:25:16
            at makeCall (/var/app/current/node_modules/fastseries/series.js:119:7)
            at ResultsHolder.release (/var/app/current/node_modules/fastseries/series.js:96:9)
            at Joi.validate (/var/app/current/node_modules/celebrate/lib/index.js:37:16)
            at internals.Object._validateWithOptions (/var/app/current/node_modules/joi/lib/types/any/index.js:654:20)
            at module.exports.internals.Any.root.validate (/var/app/current/node_modules/joi/lib/index.js:121:23)
            at /var/app/current/node_modules/celebrate/lib/index.js:28:11
            at makeCall (/var/app/current/node_modules/fastseries/series.js:119:7)
          name: 'error',
          length: 143,
          severity: 'ERROR',
          code: '25P02',
          detail: undefined,
          hint: undefined,
          position: undefined,
          internalPosition: undefined,
          internalQuery: undefined,
          where: undefined,
          schema: undefined,
          table: undefined,
          column: undefined,
          dataType: undefined,
          constraint: undefined,
          file: 'postgres.c',
          line: '999',
          routine: 'exec_simple_query' }
        2: { error: current transaction is aborted, commands ignored until end of transaction block
            at Connection.parseE (/var/app/current/node_modules/pg/lib/connection.js:539:11)
            at Connection.parseMessage (/var/app/current/node_modules/pg/lib/connection.js:366:17)
            at TLSSocket.<anonymous> (/var/app/current/node_modules/pg/lib/connection.js:105:22)
            at emitOne (events.js:116:13)
            at TLSSocket.emit (events.js:211:7)
            at addChunk (_stream_readable.js:263:12)
            at readableAddChunk (_stream_readable.js:250:11)
            at TLSSocket.Readable.push (_stream_readable.js:208:10)
            at TLSWrap.onread (net.js:594:20)
        From previous event:
            at promise (/var/app/current/node_modules/pg-promise/lib/promise.js:23:20)
            at Task.$query (/var/app/current/node_modules/pg-promise/lib/query.js:128:12)
            at Task.<anonymous> (/var/app/current/node_modules/pg-promise/lib/query.js:231:23)
            at Task.query (/var/app/current/node_modules/pg-promise/lib/task.js:119:34)
            at Task.obj.none (/var/app/current/node_modules/pg-promise/lib/database.js:368:30)
            at /var/app/current/dist/api/routes/cards/model.js:1129:22
            at Array.map (<anonymous>)
            at Task.<anonymous> (/var/app/current/dist/api/routes/cards/model.js:1126:34)
            at callback (/var/app/current/node_modules/pg-promise/lib/task.js:188:25)
            at begin.then (/var/app/current/node_modules/pg-promise/lib/task.js:233:28)
        From previous event:
            at Function.Task.exec (/var/app/current/node_modules/pg-promise/lib/task.js:232:14)
            at config.$npm.connect.pool.then.db (/var/app/current/node_modules/pg-promise/lib/database.js:1219:45)
        From previous event:
            at Database.taskProcessor (/var/app/current/node_modules/pg-promise/lib/database.js:1216:18)
            at Database.obj.tx (/var/app/current/node_modules/pg-promise/lib/database.js:1159:34)
            at /var/app/current/dist/api/routes/cards/model.js:1122:12
        From previous event:
            at Object.submitReport (/var/app/current/dist/api/routes/cards/model.js:1079:14)
            at /var/app/current/dist/api/routes/cards/index.js:1702:56
            at runCallback (timers.js:789:20)
            at tryOnImmediate (timers.js:751:5)
            at processImmediate [as _immediateCallback] (timers.js:722:5)
        From previous event:
            at /var/app/current/dist/api/routes/cards/index.js:1675:76
            at Layer.handle [as handle_request] (/var/app/current/node_modules/express/lib/router/layer.js:95:5)
            at next (/var/app/current/node_modules/express/lib/router/route.js:137:13)
            at ResultsHolder.release (/var/app/current/node_modules/fastseries/series.js:99:22)
            at Joi.validate (/var/app/current/node_modules/celebrate/lib/index.js:37:16)
            at internals.Object._validateWithOptions (/var/app/current/node_modules/joi/lib/types/any/index.js:654:20)
            at module.exports.internals.Any.root.validate (/var/app/current/node_modules/joi/lib/index.js:121:23)
            at /var/app/current/node_modules/celebrate/lib/index.js:28:11
            at /var/app/current/node_modules/celebrate/lib/index.js:53:9
            at makeCall (/var/app/current/node_modules/fastseries/series.js:119:7)
            at ResultsHolder.release (/var/app/current/node_modules/fastseries/series.js:96:9)
            at /var/app/current/node_modules/celebrate/lib/index.js:25:16
            at makeCall (/var/app/current/node_modules/fastseries/series.js:119:7)
            at ResultsHolder.release (/var/app/current/node_modules/fastseries/series.js:96:9)
            at Joi.validate (/var/app/current/node_modules/celebrate/lib/index.js:37:16)
            at internals.Object._validateWithOptions (/var/app/current/node_modules/joi/lib/types/any/index.js:654:20)
            at module.exports.internals.Any.root.validate (/var/app/current/node_modules/joi/lib/index.js:121:23)
            at /var/app/current/node_modules/celebrate/lib/index.js:28:11
            at makeCall (/var/app/current/node_modules/fastseries/series.js:119:7)
          name: 'error',
          length: 143,
          severity: 'ERROR',
          code: '25P02',
          detail: undefined,
          hint: undefined,
          position: undefined,
          internalPosition: undefined,
          internalQuery: undefined,
          where: undefined,
          schema: undefined,
          table: undefined,
          column: undefined,
          dataType: undefined,
          constraint: undefined,
          file: 'postgres.c',
          line: '999',
          routine: 'exec_simple_query' }
    ]
}
    at check (/var/app/current/node_modules/spex/lib/ext/batch.js:133:32)
    at step (/var/app/current/node_modules/spex/lib/ext/batch.js:107:17)
    at /var/app/current/node_modules/spex/lib/ext/batch.js:82:17
    at /var/app/current/node_modules/spex/lib/utils/index.js:62:25
From previous event:
    at promise (/var/app/current/node_modules/spex/lib/index.js:93:24)
    at Task.batch (/var/app/current/node_modules/spex/lib/ext/batch.js:72:12)
    at Task.<anonymous> (/var/app/current/node_modules/spex/lib/ext/batch.js:150:22)
    at Task.batch (/var/app/current/node_modules/pg-promise/lib/task.js:135:39)
    at Task.<anonymous> (/var/app/current/dist/api/routes/cards/model.js:1126:20)
    at callback (/var/app/current/node_modules/pg-promise/lib/task.js:188:25)
    at begin.then (/var/app/current/node_modules/pg-promise/lib/task.js:233:28)
From previous event:
    at Function.Task.exec (/var/app/current/node_modules/pg-promise/lib/task.js:232:14)
    at config.$npm.connect.pool.then.db (/var/app/current/node_modules/pg-promise/lib/database.js:1219:45)
From previous event:
    at Database.taskProcessor (/var/app/current/node_modules/pg-promise/lib/database.js:1216:18)
    at Database.obj.tx (/var/app/current/node_modules/pg-promise/lib/database.js:1159:34)
    at /var/app/current/dist/api/routes/cards/model.js:1122:12
From previous event:
    at Object.submitReport (/var/app/current/dist/api/routes/cards/model.js:1079:14)
    at /var/app/current/dist/api/routes/cards/index.js:1702:56
    at runCallback (timers.js:789:20)
    at tryOnImmediate (timers.js:751:5)
    at processImmediate [as _immediateCallback] (timers.js:722:5)
From previous event:
    at /var/app/current/dist/api/routes/cards/index.js:1675:76
    at Layer.handle [as handle_request] (/var/app/current/node_modules/express/lib/router/layer.js:95:5)
    at next (/var/app/current/node_modules/express/lib/router/route.js:137:13)
    at ResultsHolder.release (/var/app/current/node_modules/fastseries/series.js:99:22)
    at Joi.validate (/var/app/current/node_modules/celebrate/lib/index.js:37:16)
    at internals.Object._validateWithOptions (/var/app/current/node_modules/joi/lib/types/any/index.js:654:20)
    at module.exports.internals.Any.root.validate (/var/app/current/node_modules/joi/lib/index.js:121:23)
    at /var/app/current/node_modules/celebrate/lib/index.js:28:11
    at /var/app/current/node_modules/celebrate/lib/index.js:53:9
    at makeCall (/var/app/current/node_modules/fastseries/series.js:119:7)
    at ResultsHolder.release (/var/app/current/node_modules/fastseries/series.js:96:9)
    at /var/app/current/node_modules/celebrate/lib/index.js:25:16
    at makeCall (/var/app/current/node_modules/fastseries/series.js:119:7)
    at ResultsHolder.release (/var/app/current/node_modules/fastseries/series.js:96:9)
    at Joi.validate (/var/app/current/node_modules/celebrate/lib/index.js:37:16)
    at internals.Object._validateWithOptions (/var/app/current/node_modules/joi/lib/types/any/index.js:654:20)
    at module.exports.internals.Any.root.validate (/var/app/current/node_modules/joi/lib/index.js:121:23)
    at /var/app/current/node_modules/celebrate/lib/index.js:28:11
    at makeCall (/var/app/current/node_modules/fastseries/series.js:119:7)
```

**Comment by matthewberryman** [comment]
Fixed with DB patch script https://github.com/urbanriskmap/cognicity-schema/issues/44
