### ISSUE TITLE
When report submitted outside area - no thank you message is received

### ISSUE THREAD

**Issue by tomasholderness** [urbanriskmap/cognicity-server#87]

**Comment by tomasholderness** [comment]
Error is with notification query that needs to happen to gather intel to be sent to the notification lambda. Log is:

```
error: column la.district_id does not exist
    at Connection.parseE (/var/app/current/node_modules/pg/lib/connection.js:539:11)
    at Connection.parseMessage (/var/app/current/node_modules/pg/lib/connection.js:366:17)
    at TLSSocket.<anonymous> (/var/app/current/node_modules/pg/lib/connection.js:105:22)
    at emitOne (events.js:116:13)
    at TLSSocket.emit (events.js:211:7)
    at addChunk (_stream_readable.js:263:12)
    at readableAddChunk (_stream_readable.js:250:11)
    at TLSSocket.Readable.push (_stream_readable.js:208:10)
    at TLSWrap.onread (net.js:594:20)
```

**Comment by tomasholderness** [comment]
Fixed over in the schema: https://github.com/urbanriskmap/cognicity-schema/commit/8ca1b9e10d7db96c09f9c2f2cf234a566df14ac3
