### ISSUE TITLE
API Cache version changes

### ISSUE THREAD

**Issue by tomasholderness** [urbanriskmap/cognicity-server#89]
When using the latest version of API cache we get internal errors (not from our code) when accessing `/reports`

```
TypeError: toggle is not a function
    at shouldCacheResponse (/var/app/current/node_modules/apicache/src/apicache.js:74:20)
    at ServerResponse.res.end (/var/app/current/node_modules/apicache/src/apicache.js:188:11)
    at Array.write (/var/app/current/node_modules/finalhandler/index.js:297:9)
    at listener (/var/app/current/node_modules/on-finished/index.js:169:15)
    at onFinish (/var/app/current/node_modules/on-finished/index.js:100:5)
    at callback (/var/app/current/node_modules/ee-first/index.js:55:10)
    at IncomingMessage.onevent (/var/app/current/node_modules/ee-first/index.js:93:5)
    at emitNone (events.js:106:13)
    at IncomingMessage.emit (events.js:208:7)
    at endReadableNT (_stream_readable.js:1056:12)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickDomainCallback (internal/process/next_tick.js:218:9)
```

**Comment by tomasholderness** [comment]
Rolled back version for now (4347898e280d284cb561e5c4d5292da142c587c0). Bump this for next major/point release
